version: "3.8"
services:
    app_creator_web:
        image: gluontech/app_creator_web:1.0.1
        restart: unless-stopped
        ports:
            - ${WEB_APP_PORT}:80
        environment:
          API_URL: ${API_APP_DOMAIN}
        networks:
            - app_creator_network

    app_creator_api:
        image: gluontech/app_creator_api:1.0.1
        restart: unless-stopped
        depends_on:
            - app_creator_mysql
        networks:
            - app_creator_network

    app_creator_nginx:
        image: nginx:stable-alpine
        restart: unless-stopped
        ports:
            - ${API_APP_PORT}:80
        volumes:
            - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - app_creator_api
        networks:
            - app_creator_network

    app_creator_scheduler:
        image: gluontech/app_creator_scheduler:1.0.1
        restart: unless-stopped
        depends_on:
            - app_creator_api
            - app_creator_mysql
        networks:
            - app_creator_network

    app_creator_mysql:
        image: mysql:8.0
        restart: unless-stopped
        tty: true
        ports:
            - ${DB_PORT}:3306
        volumes:
            - ./database/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        networks:
            - app_creator_network

networks:
    app_creator_network:
        driver: bridge
